### ISSUE TITLE
Support for CLIENT_ACKNOWLEDGE mode

### ISSUE THREAD

**Issue by youngm** [egetman/reactive-jms#2]
Thought much about supporting CLIENT_ACKNOWLEDGE mode?  I see you have transaction support but not all queue providers that support JMS support transactions.

Thanks

**Comment by egetman** [comment]
Hi, @youngm.
It sounds reasonable. 
There 2 simple ways of doing it: create a new constructor to `UnicastJmsQueueSource`, or modify the existing one (with transacted param).
Do you wanna to create a PR?

**Comment by youngm** [comment]
@egetman I may.  We were thinking of using this library for a project so I asked the question.  But it looks like the project may go another direction.  Feel free to close this issue and I'll reopen and submit a PR if we end up going this direction again.  Thanks!

**Comment by egetman** [comment]
@youngm done.
